require 'rubygems'
require "rake/testtask"
task :default => [:test]

desc "Run tests"
Rake::TestTask.new do |t|
  t.libs << ["test"]
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end

desc "Package dumbapp"
task :package do
  
end